### PR TITLE
fixes minor coding standard issues

### PR DESCRIPTION
**Pull request by AronNovak**

### CODE REVIEW

**Comment by amitaibu** [comment]
@HelenaEksler care to review? 😄

**Comment by amitaibu** [comment]
Seems she's not around. @nader77 can you review the Pull-request**s** please

**Comment by nedSaf** [comment]
Sure.

**Comment by nedSaf** [comment]
@amitaibu Looks good, should I merge ?

**Comment by amitaibu** [comment]
> should I merge ?

It's your module dude :)

**Comment by nedSaf** [comment]
@AronNovak Thanks mate  :)

**Pull request merged**
