### PR TITLE
fixes minor coding standard issues for 8.x

### PR DESCRIPTION
**Pull request by AronNovak**

### CODE REVIEW

**Comment by nedSaf** [comment]
@AronNovak Is this ready ?

**Comment by AronNovak** [comment]
Indeed, it is supposed to be.

**Comment by nedSaf** [comment]
Cheers, Thanks.

**Comment by amitaibu** [comment]
(Make sure to push to d.o. as well)

**Comment by nedSaf** [comment]
Will do.

**Pull request merged**
