### PR TITLE
Improve readme file.

### PR DESCRIPTION
**Pull request by nedSaf**

### CODE REVIEW

**Comment by nedSaf** [comment]
README file:
csv2sql_readme_md_at_b165a61647665049b2b15504e1e7eb5a41d36c18_ _nader77_csv2sql

**Comment by nedSaf** [comment]
@ordavidil Would love your input if this is a more clear instructions, any suggestion is welcomed :)

**Comment by nedSaf** [comment]
Will do the same for `8.x` once this is finalized.

**Comment by ordavidil** [comment]
@nader77 
should we add #23 and the other options as well ?

**Comment by nedSaf** [comment]
👍

**Comment by nedSaf** [comment]
csv2sql_readme_md_at_adcd4e4cb5fcbf99146c8541621da7f1a15045ad_ _nader77_csv2sql
csv2sql_readme_md_at_adcd4e4cb5fcbf99146c8541621da7f1a15045ad_ _nader77_csv2sql

**Pull request merged**
